server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/sufragio/ {
        proxy_pass http://servicio-sufragio:3001/api/sufragio/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/auditoria/ {
        proxy_pass http://servicio-auditoria:3003/api/auditoria/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}