version: '3.8'

services:
  # Broker de mensajería central
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: evoting-broker
    ports:
      - "5672:5672"
      - "15672:15672"

  # --- SERVICIO 1: GESTIÓN DE SUFRAGIO ---
  db-sufragio:
    image: postgres:15-alpine
    container_name: db-sufragio
    environment:
      POSTGRES_DB: db_sufragio
      POSTGRES_PASSWORD: secret_sufragio
    volumes:
      - data-sufragio:/var/lib/postgresql/data

  servicio-sufragio:
    build: ./servicio-1-sufragio
    container_name: s1-sufragio
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_URI=postgres://postgres:secret_sufragio@db-sufragio:5432/db_sufragio
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq
      - db-sufragio

  # --- SERVICIO 2: PADRÓN ELECTORAL ---
  db-padron:
    image: postgres:15-alpine
    container_name: db-padron
    environment:
      POSTGRES_DB: db_padron
      POSTGRES_PASSWORD: secret_padron
    volumes:
      - data-padron:/var/lib/postgresql/data

  servicio-padron:
    build: ./servicio-2-padron
    container_name: s2-padron
    environment:
      - DB_URI=postgres://postgres:secret_padron@db-padron:5432/db_padron
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq
      - db-padron

  # --- SERVICIO 3: REGISTRO DE AUDITORÍA ---
  db-auditoria:
    image: postgres:15-alpine
    container_name: db-auditoria
    environment:
      POSTGRES_DB: db_auditoria
      POSTGRES_PASSWORD: secret_auditoria
    volumes:
      - data-auditoria:/var/lib/postgresql/data

  servicio-auditoria:
    build: ./servicio-3-auditoria
    container_name: s3-auditoria
    environment:
      - DB_URI=postgres://postgres:secret_auditoria@db-auditoria:5432/db_auditoria
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq
      - db-auditoria

volumes:
  data-sufragio:
  data-padron:
  data-auditoria: