# --- ETAPA 1: CONSTRUCCIÓN (BUILDER) ---
FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

# --- ETAPA 2: PRODUCCIÓN (ENTORNO LIGERO) ---
FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY --from=builder /usr/src/app ./

ENV NODE_ENV=production

EXPOSE 3001

CMD ["node", "src/index.js"]