apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # NOTA: Los Secrets se crean manualmente en el cluster. Ver k8s/base/secrets/secrets.yaml.example
  - network-policy.yaml
  - rabbitmq/pvc.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - postgres-sufragio/all.yaml
  - postgres-padron/all.yaml
  - postgres-auditoria/all.yaml
  - servicio-sufragio/all.yaml
  - servicio-padron/all.yaml
  - servicio-auditoria/all.yaml
  - frontend/all.yaml 


configMapGenerator:
  - name: init-sufragio-sql
    files:
      - init.sql=db-init/init-sufragio.sql
  - name: init-padron-sql
    files:
      - init.sql=db-init/init-padron.sql
  - name: init-auditoria-sql
    files:
      - init.sql=db-init/init-auditoria.sql

labels:
  - includeSelectors: false
    pairs:
      proyecto: evoting
